🔧: Fixed amount units in stock
Carbonable/carbonable-ccrp-backend pull request #109
Opened 2024-09-09 16:56 UTC by LouGel

2024-09-09 19:52 UTC, MartianGreed requested changes

2024-09-09 19:52 UTC, MartianGreed commented on src/domain/order-book/stock-manager.ts
> +      const splitStock = Math.round(
we might want to check with business if we get the upper bound or the lower bound when getting percentage of available carbon units.

2024-09-09 19:52 UTC, MartianGreed commented on src/domain/order-book/stock-manager.ts
> +      const issued = issuedCount > 0 ? splitStock : 0;
previous line needs to be updated too

2024-09-10 08:57 UTC, closed without merging

2024-09-10 08:58 UTC, LouGel commented
Already used in the next PR from @MartianGreed